package alladt.Hibernate.Hibernate566final.Conf;
// Generated 2 jun 2024 16:30:31 by Hibernate Tools 5.6.15.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Set personajeses = new HashSet(0);

	public Empresa() {
	}

	public Empresa(String nombre) {
		this.nombre = nombre;
	}

	public Empresa(String nombre, Set personajeses) {
		this.nombre = nombre;
		this.personajeses = personajeses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getPersonajeses() {
		return this.personajeses;
	}

	public void setPersonajeses(Set personajeses) {
		this.personajeses = personajeses;
	}

}
