package alladt.Hibernate.Hibernate566final.Conf;
// Generated 2 jun 2024 16:30:31 by Hibernate Tools 5.6.15.Final

/**
 * Personajes generated by hbm2java
 */
public class Personajes implements java.io.Serializable {

	private Integer id;
	private Empresa empresa;
	private String nombre;
	private String juego;

	public Personajes() {
	}

	public Personajes(String nombre, String juego) {
		this.nombre = nombre;
		this.juego = juego;
	}

	public Personajes(Empresa empresa, String nombre, String juego) {
		this.empresa = empresa;
		this.nombre = nombre;
		this.juego = juego;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getJuego() {
		return this.juego;
	}

	public void setJuego(String juego) {
		this.juego = juego;
	}

}
